"""empty message

Revision ID: 1778db3149ec
Revises: 0ea6fdd0bc88
Create Date: 2019-07-07 16:14:44.629456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1778db3149ec'
down_revision = '0ea6fdd0bc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('like_count', sa.Integer(), nullable=False))
    op.drop_column('events', 'like')
    op.add_column('like_event', sa.Column('isLiked', sa.Integer(), nullable=True))
    op.drop_column('like_event', 'like_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like_event', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('like_event', 'isLiked')
    op.add_column('events', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('events', 'like_count')
    # ### end Alembic commands ###
