"""empty message

Revision ID: 956902a2a7be
Revises: 29986b354dbb
Create Date: 2019-07-08 21:57:21.562565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956902a2a7be'
down_revision = '29986b354dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('total_tickets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'total_tickets')
    # ### end Alembic commands ###
