"""empty message

Revision ID: dadbd821288e
Revises: 1778db3149ec
Create Date: 2019-07-07 16:34:16.930812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadbd821288e'
down_revision = '1778db3149ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like_event', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'like_event', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'like_event', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like_event', type_='foreignkey')
    op.drop_constraint(None, 'like_event', type_='foreignkey')
    op.alter_column('like_event', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like_event', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
