"""empty message

Revision ID: df74d8c16213
Revises: 956902a2a7be
Create Date: 2019-07-08 22:01:12.765620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df74d8c16213'
down_revision = '956902a2a7be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'total_tickets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('total_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
